import BtnNavbar from "@/app/components/features/ui/btn_navbar/btn_navbar";
import Navbar from "@/app/components/features/Navbar/navbar";
import Modal from "@/app/components/features/modal/modal";
import Pagination from "@/app/components/features/pagination/pagination";
import Location from "@/app/components/features/contacts/location";
export {BtnNavbar as BtnNavbar}
export {Navbar as Navbar}
export {Modal as Modal}
export {Pagination as Pagination}
export {Location as Location}