import TakeDate from "@/app/components/widgets/takeDate/takeDate";
import StudioRooms from "@/app/components/widgets/StudioRooms/StudioRooms";
import SetkaFourth from "@/app/components/widgets/setkaFourth/setkaFourth";
import Slider from "@/app/components/widgets/slider/slider";
import SetkaSixth from "@/app/components/widgets/setkaSixth/setkaSixth";
import Footer from "@/app/components/widgets/footer/footer";
import SliderTeam from "@/app/components/widgets/slider/team";
export {TakeDate as TakeDate}
export {StudioRooms as StudioRooms}
export {SetkaFourth as SetkaFourth}
export {Slider as Slider}
export {SetkaSixth as SetkaSixth}
export {Footer as Footer}
export {SliderTeam as SliderTeam}